### PR TITLE
Fix error handling for multiple functions returning status codes

### PR DESCRIPTION
**Pull request by civanahmetyasin**
This pull request addresses the error handling in multiple functions within the INA230 driver. Specifically, the changes ensure that the return status from the ina230_readreg function is properly checked and handled in various functions to prevent incorrect data usage in case of a read failure. The following improvements have been made:

Error Handling:

Updated multiple functions to correctly handle the return status of ina230_readreg, ensuring that errors are detected and handled properly.
When an error occurs, functions now return predefined error codes (e.g., INA230_E_READ_FAIL) to indicate failure, thus avoiding unexpected behavior.
Code Consistency:

Ensured that the same approach is followed across different functions for better maintainability and readability.
Standardized the use of error codes and success status macros throughout the codebase (INA230_OK, INA230_SCS).
Safety Checks:

Added null pointer checks and validation in functions where the INA230 device handler is passed as a parameter.
This update improves the robustness of the driver and ensures more predictable behavior when errors occur during I2C register reads.

Disclaimers:
English: Please note that these changes have been made to the best of my understanding, and they may require further testing and validation. I am not liable for any issues that may arise from the implementation of these changes.

Türkçe: Lütfen bu değişikliklerin en iyi anlayışımla yapıldığını ve daha fazla test ve doğrulama gerektirebileceğini unutmayın. Bu değişikliklerin uygulanmasından kaynaklanabilecek herhangi bir sorun için sorumluluk kabul edilmemektedir.

### CODE REVIEW

**Comment by bcwaldon** [comment]
Hi @civanahmetyasin - thanks for the PR! We will review and get back to you soon.

**Comment by civanahmetyasin** [comment]
Hi @bcwaldon 

Thank you for the update! I look forward to your feedback.

Best regards,
Ahmet Yasin Civan

**Comment by bcwaldon** [comment]
Hi @civanahmetyasin I just wanted to let you know we have not forgotten about this! The team is just preoccupied with some high priority mission milestones right now. We will revert back soon.

**Comment by civanahmetyasin** [comment]
Hi @bcwaldon, thank you for the update! I completely understand the team’s priorities and appreciate you letting me know. Looking forward to hearing back when things settle down. Let me know if there's anything I can assist with in the meantime!

**Comment by bcwaldon** [comment]
Thanks for the contribution! We will make sure this gets included in the next release we are working on.

**Pull request merged**
